name: event_bus
version: 2.0.1
description: A simple Event Bus using Dart Streams for decoupling applications
# original repo: https://github.com/marcojakob/dart-event-bus
repository: https://github.com/msbeaule/dart-event-bus
# homepage: https://code.makery.ch/library/dart-event-bus/
environment:
  sdk: '>=2.12.0 <3.0.0'
dev_dependencies:
  build_runner: ^2.4.8
  build_web_compilers: ^4.0.9
  build_test: ^2.2.2
  logging: ^1.2.0
  test: ^1.25.2
